# Copyright 2021 root
# See LICENSE file for licensing details.

options:
  s6aPort:
    default: 3868
    description: S6A Port to be used
    type: int 
  promExporterPort:
    default: 9080
    description: Prometheus Port to be used
    type: int 
